// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Hp72nB7a0Bb0f6vZbI1AR_-wGz0v8vk',
    appId: '1:886591291200:web:66431af436a14d620a84a5',
    messagingSenderId: '886591291200',
    projectId: 'dmt-seba-eaf1f',
    authDomain: 'dmt-seba-eaf1f.firebaseapp.com',
    storageBucket: 'dmt-seba-eaf1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvZ9sKwo9N8GgAOOvbGmAgMhA5qsKaVDo',
    appId: '1:886591291200:android:cadafd04df8bd75f0a84a5',
    messagingSenderId: '886591291200',
    projectId: 'dmt-seba-eaf1f',
    storageBucket: 'dmt-seba-eaf1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-Bp3YGmV3gYoG6__9XxXcNbexg2oEyg',
    appId: '1:886591291200:ios:7d5d74c555457a0e0a84a5',
    messagingSenderId: '886591291200',
    projectId: 'dmt-seba-eaf1f',
    storageBucket: 'dmt-seba-eaf1f.firebasestorage.app',
    iosBundleId: 'com.example.dmtSeba',
  );
}
